service: serverless-http-api-typescript

# todo: 2のままで動かす方法を調べる
# frameworkVersion: '2'
frameworkVersion: '1'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
  # なかったので追記。AWS上で影響がないことは確認したほうがいいかも
  - serverless-offline
